/* int layer0[44] = { */
/*     KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_0, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P,  */
/*     KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_0, KEY_H, KEY_J, KEY_K, KEY_L, KEY_SEMICOLON,  */
/*     KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEYBOARD_LEFT_ALT, KEY_N, KEY_M, KEY_COMMA, KEY_PERIOD, KEY_SLASH,  */
/*     KEY_ESC, KEY_TAB, KEYBOARD_LEFT_GUI, KEYBOARD_LEFT_SHIFT, KEY_BACKSPACE, KEYBOARD_LEFT_CTRL, KEY_SPACE, PRE_FUNCTION(1), KEY_MINUS, KEY_QUOTE, KEY_ENTER }; */

#define KEY_PROGRAM 0x00
#define KEY_KEYPAD 0x00

int layer0[105] = {
  KEY_EQUAL, KEY_TAB, KEY_CAPS_LOCK, KEYBOARD_LEFT_SHIFT, KEY_DUMMY, KEY_DUMMY, KEY_DUMMY,
  KEY_1, KEY_Q, KEY_A, KEY_Z, KEY_TILDE, KEY_DUMMY, KEY_DUMMY,
  KEY_2, KEY_W, KEY_S, KEY_X, KEY_INSERT, KEY_END, KEY_DUMMY,
  KEY_3, KEY_E, KEY_D, KEY_C, KEY_LEFT, KEY_HOME,  KEY_BACKSPACE,
  KEY_4, KEY_R, KEY_F, KEY_V, KEY_DUMMY, KEY_DUMMY, KEY_DELETE,
  KEY_5, KEY_T, KEY_G, KEY_B, KEY_RIGHT, KEYBOARD_LEFT_ALT, KEYBOARD_LFT_CTRL,

  KEY_6, KEY_Y, KEY_H, KEY_N, KEY_UP, KEY_SPACE, KEY_PAGE_DOWN,
  KEY_7, KEY_U, KEY_J, KEY_M, KEY_DUMMY, KEY_ENTER, KEY_DUMMY,
  KEY_8, KEY_I, KEY_K, KEY_COMMA, KEY_DOWN, KEYBOARD_RIGHT_CTRL, KEY_PAGE_UP,

  KEY_9, KEY_O, KEY_L, KEY_PERIOD, KEY_LEFT_BRACE, KEY_DUMMY, KEY_RIGHT_ALT,

  KEY_0, KEY_P, KEY_SEMICOLON, KEY_SLASH, KEY_RIGHT_BRACE, KEY_DUMMY, KEY_DUMMY,
  KEY_MINUS, KEY_BACKSLASH, KEY_QUOTE, KEY_RIGHT_SHIFT, KEY_DUMMY, KEY_DUMMY, KEY_DUMMY,
  KEY_ESC, KEY_F3, KEY_F6, KEY_F9, KEY_F12, KEY_PAUSE, KEY_DUMMY,
  KEY_F1, KEY_F4, KEY_F7, KEY_F10, KEY_PRINTSCREEN, KEY_PROGRAM, KEY_DUMMY,
  KEY_F2, KEY_F5, KEY_F8, KEY_F11, KEY_SCROLL_LOCK, KEY_KEYPAD, KEY_DUMMY,
};

int layer1[44] = {
    SHIFT(KEY_1), SHIFT(KEY_2), SHIFT(KEY_LEFT_BRACE), SHIFT(KEY_RIGHT_BRACE), SHIFT(KEY_BACKSLASH), KEY_0, KEY_PAGE_UP, KEY_7, KEY_8, KEY_9, SHIFT(KEY_8),
    SHIFT(KEY_3), SHIFT(KEY_4), SHIFT(KEY_9), SHIFT(KEY_0), KEY_TILDE, KEY_0, KEY_PAGE_DOWN, KEY_4, KEY_5, KEY_6, SHIFT(KEY_EQUAL),
    SHIFT(KEY_5), SHIFT(KEY_6), KEY_LEFT_BRACE, KEY_RIGHT_BRACE, SHIFT(KEY_TILDE), KEYBOARD_LEFT_ALT, SHIFT(KEY_7), KEY_1, KEY_2, KEY_3, KEY_BACKSLASH,
    FUNCTION(2), SHIFT(KEY_INSERT), KEYBOARD_LEFT_GUI, KEYBOARD_LEFT_SHIFT, KEY_BACKSPACE, KEYBOARD_LEFT_CTRL, KEY_SPACE, PRE_FUNCTION(1), KEY_PERIOD, KEY_0, KEY_EQUAL };

int layer2[44] = {
    KEY_HOME, KEY_UP, KEY_END, KEY_INSERT, KEY_PAGE_UP, KEY_0, KEY_UP, KEY_F7, KEY_F8, KEY_F9, KEY_F10,
    KEY_LEFT, KEY_DOWN, KEY_RIGHT, KEY_DELETE, KEY_PAGE_DOWN, KEY_0, KEY_DOWN, KEY_F4, KEY_F5, KEY_F6, KEY_F11,
    0, 0, 0, 0, 0, KEYBOARD_LEFT_ALT, 0, KEY_F1, KEY_F2, KEY_F3, KEY_F12,
    LAYER(0), 0, KEYBOARD_LEFT_GUI, KEYBOARD_LEFT_SHIFT, KEY_BACKSPACE, KEYBOARD_LEFT_CTRL, KEY_SPACE, PRE_FUNCTION(1), 0, 0, FUNCTION(0) };

int *layers[] = {layer0, layer1, layer2};

#include "layout_common.h"
